AWSTemplateFormatVersion: '2010-09-09'
Description: Spotify Playlist Sync

Parameters:
  LambdaArn:
    Type: String
    AllowedPattern: arn:(aws[a-zA-Z-]*)?:lambda:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9-_]+

  ConnectArn:
    Type: String
    AllowedPattern: arn:aws:connect:[a-z]*-[a-z]*-\d:\d{12}:instance/[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{12}

Resources:
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaArn
      Principal: connect.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Ref ConnectArn
